name: Dynamic Matrix build

on:
  workflow_dispatch:
    inputs:
          x:
            description: 'Number of jobs on x-Axis'
            required: true
            default: '8'
          y:
            description: 'Number of jobs on y-Axis'
            required: true
            default: '4'

jobs:
  generate-matrix:
    name: "Generate matrix job specs"
    outputs:
      x: ${{ steps.generate-matrix.outputs.x }}
      y: ${{ steps.generate-matrix.outputs.y }}
    runs-on: ubuntu-latest
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          echo "::set-output name=x::[`seq -s , ${{ github.event.inputs.x }}`]"
          echo "::set-output name=y::[`seq -s , ${{ github.event.inputs.y }}`]"

  matrix:
      name: "Matrix job"
      runs-on: ubuntu-latest
      needs: [generate-matrix]
  
      strategy:
        fail-fast: false
        matrix:
          x: ${{ fromJson(needs.generate-matrix.outputs.x) }}
          y: ${{ fromJson(needs.generate-matrix.outputs.y) }}
      steps:
            - name: Perform job
              run: echo "${{matrix.x}}, ${{matrix.y}}"
