name: Destroy via PR unlabel
on:
  pull_request:
    types: [unlabeled]

jobs:
  permission:
    name: permission check
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
    - name: check permission
      run: echo permission pass
  debug:
    name: _debug
    needs: permission
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'debug')
    steps:
    - name: context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  deployment:
    name: Destroy via unlabel
    needs: permission
    runs-on: ubuntu-latest
    if: |
        github.event.label.name == 'azure' ||
        github.event.label.name == 'gcp' ||
        github.event.label.name == 'aws'
    steps:
    - name: ACK destroy request
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 @' + context.actor + ', tear down request for ${{ github.event.label.name }} received ...'
          })
    - name: Kicking off tear down
      uses: actions/github-script@0.5.0
      env:
        cloud: ${{ github.event.label.name }}
        customer: ${{ github.event.pull_request.head.ref }}
      with:
        github-token: ${{secrets.GPR_PAT}}
        script: |
          const { cloud, customer } = process.env;
          let customerNormalized = customer.replace(/[^a-zA-Z0-9_\-]*/g, '')
          let gprUrl='docker.pkg.github.com/'+context.repo.owner.toLowerCase()+'/'+context.repo.repo.toLowerCase()+'/octocat-generator-docker:'+customerNormalized
          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'destroy-in-'+cloud,
            client_payload: { customer: customer, cloud: cloud, gprUrl: gprUrl, issue: context.issue.number }
          })
